import 'package:co_work_connect/features/data/models/place_model.dart';

List<PlaceModel> places = [
    PlaceModel(
      name: 'WorkHub Downtown',
      address: '456 Market St, Capital City',
      phoneNumber: '555-123-9876',
      description:
          'Modern coworking hub with high-speed internet and private booths.',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKQqyxd1Aojn3QLTvUDkaWV6VpqmyeBuBTyA&s',
      openingHours: '8 AM - 6 PM',
      capacity: 60,
      price: 25,
      rating: 4.7,
      rateCount: 87,
    ),
    PlaceModel(
      name: 'The Creative Corner',
      address: '789 Innovation Ave, Metro City',
      phoneNumber: '555-987-6543',
      description: 'Ideal for designers and freelancers seeking a quiet space.',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC_W6kcHB_uLAbl5hpY46snjNKNIFEGxxKwg&s',
      openingHours: '10 AM - 7 PM',
      capacity: 40,
      price: 18,
      rating: 4.3,
      rateCount: 65,
    ),
    PlaceModel(
      name: 'Startup Base',
      address: '321 Tech Road, Startup Valley',
      phoneNumber: '555-321-9999',
      description: 'Perfect for tech startups with flexible desk options.',
      imageUrl:
          'https://images.squarespace-cdn.com/content/v1/5877fcf8ebbd1a0e70bf993e/1612977764262-I0UOYLBCFNVLYG0B24BY/A+desk+set+up+inside+a+shared+workspace',
      openingHours: '9:30 AM - 6 PM',
      capacity: 55,
      price: 22,
      rating: 4.6,
      rateCount: 72,
    ),
    PlaceModel(
      name: 'Leftbrain Workspace',
      address: '67 Pioneer Blvd, Business City',
      phoneNumber: '555-888-1122',
      description: 'Smart and efficient environment for productive work.',
      imageUrl:
          'https://cdn.prod.website-files.com/647b2b9a28e918e69c2237a6/64e5ea079195523329912bcf_leftbrain-google-workspace.webp',
      openingHours: '9:00 AM - 6:00 PM',
      capacity: 45,
      price: 23,
      rating: 4.4,
      rateCount: 90,
    ),
    PlaceModel(
      name: 'The Workstation',
      address: '22 Freelancer Ln, Digital City',
      phoneNumber: '555-444-7788',
      description: 'Bright and open space for all types of professionals.',
      imageUrl:
          'https://images.squarespace-cdn.com/content/v1/54f6310de4b0e6d747933c7a/1715696358450-3JZ47YK00LYNT9CUER0T/2R6A2721.jpg?format=1500w',
      openingHours: '8:30 AM - 5:30 PM',
      capacity: 60,
      price: 21,
      rating: 4.5,
      rateCount: 105,
    ),
    PlaceModel(
      name: 'FocusLab Studio',
      address: '11 Quiet Place, Remote Town',
      phoneNumber: '555-222-3344',
      description: 'Tailored for developers and researchers who need focus.',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCyxyxyr9lb48sjj9k46z9zwH-2AUUuMRgww&s',
      openingHours: '7 AM - 3 PM',
      capacity: 35,
      price: 19,
      rating: 4.2,
      rateCount: 80,
    ),
    PlaceModel(
      name: 'Harmony Hall',
      address: '910 Zen St, Green City',
      phoneNumber: '555-777-1010',
      description: 'Eco-friendly space with a calm and inspiring vibe.',
      imageUrl:
          'https://www.goodworks.in/wp-content/uploads/2020/06/An-Aftermath-Of-COVID-19-Pandemic-The-Future-Of-Workspaces.jpeg',
      openingHours: '10 AM - 4 PM',
      capacity: 50,
      price: 20,
      rating: 4.5,
      rateCount: 100,
    ),
    PlaceModel(
      name: 'Freelance Forge',
      address: '101 Workshop Rd, Creativille',
      phoneNumber: '555-111-2323',
      description: 'A melting pot of artists, coders, and writers.',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzEf1F3rVBHR3vSF1vO1hft0CWHMOyu4ol0Q&s',
      openingHours: '11 AM - 7 PM',
      capacity: 38,
      price: 17,
      rating: 4.0,
      rateCount: 58,
    ),
    PlaceModel(
      name: 'The Hive Spot',
      address: '5 Community Dr, HiveTown',
      phoneNumber: '555-666-9090',
      description: 'Connect, create, and thrive in this shared space.',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLY7GuZZ1p1ChUQTt7LXToV7aiMlE5U0TpsA&s',
      openingHours: '8 AM - 8 PM',
      capacity: 70,
      price: 26,
      rating: 4.8,
      rateCount: 130,
    ),
    PlaceModel(
      name: 'Coworking Space 1',
      address: '123 Main St, City',
      phoneNumber: '123-456-7890',
      description: 'A great place to work and collaborate.',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKQqyxd1Aojn3QLTvUDkaWV6VpqmyeBuBTyA&s',
      openingHours: '9 AM - 5 PM',
      capacity: 50,
      price: 20,
      rating: 4.5,
      rateCount: 100,
    ),
    PlaceModel(
      name: 'Coworking Space 2',
      address: '123 Main St, City',
      phoneNumber: '123-456-7890',
      description: 'A great place to work and collaborate.',
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC_W6kcHB_uLAbl5hpY46snjNKNIFEGxxKwg&s',
      openingHours: '9 AM - 5 PM',
      capacity: 50,
      price: 40,
      rating: 4.5,
      rateCount: 100,
    ),
    PlaceModel(
      name: 'Coworking Space 3',
      address: '123 Main St, City',
      phoneNumber: '123-456-7890',
      description: 'A great place to work and collaborate.',
      imageUrl:
          'https://images.squarespace-cdn.com/content/v1/5877fcf8ebbd1a0e70bf993e/1612977764262-I0UOYLBCFNVLYG0B24BY/A+desk+set+up+inside+a+shared+workspace',
      openingHours: '9 AM - 5 PM',
      capacity: 50,
      price: 50,
      rating: 4.5,
      rateCount: 100,
    ),
  ];